Solution ← { 1+¯1⊐˜+´¨(1↓↑)∘((-(')'⊸=))+('('⊸=))𝕩 }

•Out "Tests:"
•Out "(()):"
•Show Solution "(())"
•Out "()():"
•Show Solution "()()"
•Out "(((:"
•Show Solution "((("
•Out "(()(()(:"
•Show Solution "(()(()("
•Out "))(((((:"
•Show Solution "))((((("
•Out "()):"
•Show Solution "())"
•Out "))(:"
•Show Solution "))("
•Out "))):"
•Show Solution ")))"
•Out ")())()):"
•Show Solution ")())())"


•Out ""
•Out "Personal input:"
•Show Solution •FChars "d01.input"


